### ISSUE TITLE
Local Variable is Global

### ISSUE THREAD

**Issue by KhayaDillon** [learn-co-curriculum/skills-based-js-intro-to-variables#16]
In the CHANGING VARIABLE VALUES section, "Local variable assignment can overwrite global variable assignment" confused me and made me think it meant a local variable can overwrite a global one, when it really meant a global variable assignment inside a function can overwrite the one outside the function. Can be confusing for people just learning. It made me confused on what defines a local vs. global variable. First reading it made me thing that a variable assignment inside a function, but without var in front, was local, when it's actually global.

**Comment by maxwellbenton** [comment]
Hi @KhayaDillon,

Thank you for providing this feedback. We've updated this lesson's instructions to further clarify the difference between local and global variables and how they behave based on your feedback.

We apologize for and confusion this may have caused, but we appreciate you letting us know so that we can improve our content for future students.

Thank you!
