### ISSUE TITLE
Const and Let?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/skills-based-js-intro-to-variables#3]
Are they important this early on in the curriculum? Do you test it in following labs?

**Comment by pletcher** [comment]
I think there are good reasons to prefer `const` and `let` over `var` -- hoisting, for one, is really weird behavior for most people, and it leads to subtle and sometimes hard to detect bugs.

I will work on a way to test them. Because of how they're scoped (one of their virtues!), this might be tricky.
